
-- DROP TABLES (IF EXISTS)
DROP TABLE IF EXISTS order_item_extras;
DROP TABLE IF EXISTS order_item_ingredients;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS product_ingredients;
DROP TABLE IF EXISTS product_extras;
DROP TABLE IF EXISTS extras;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS daily_order_counter;
DROP TABLE IF EXISTS categories;

-- CATEGORIES
CREATE TABLE categories (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(50) NOT NULL
);

-- INGREDIENTS
CREATE TABLE ingredients (
                             id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(50) NOT NULL
);

-- EXTRAS
CREATE TABLE extras (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(50) NOT NULL,
                        price_cents INT NOT NULL CHECK (price_cents >= 0)
);

-- PRODUCTS
CREATE TABLE products (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(50) NOT NULL,
                          price_cents INT NOT NULL CHECK (price_cents >= 0),
                          category_id INT,
                          CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- PRODUCT INGREDIENTS
CREATE TABLE product_ingredients (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     product_id INT NOT NULL,
                                     ingredient_id INT NOT NULL,
                                     CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id),
                                     CONSTRAINT fk_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

-- PRODUCT EXTRAS
CREATE TABLE product_extras (
                                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                product_id INT NOT NULL,
                                extra_id INT NOT NULL,
                                CONSTRAINT fk_product_extra FOREIGN KEY (product_id) REFERENCES products(id),
                                CONSTRAINT fk_extra FOREIGN KEY (extra_id) REFERENCES extras(id)
);

-- ORDERS
CREATE TABLE orders (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_number VARCHAR(20) NOT NULL UNIQUE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        total_price_cents INT NOT NULL CHECK (total_price_cents >= 0)
);

-- ORDER ITEMS
CREATE TABLE order_items (
                             id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id INT NOT NULL,
                             product_name VARCHAR(100) NOT NULL,
                             base_price_cents INT NOT NULL CHECK (base_price_cents >= 0),
                             quantity INT NOT NULL CHECK (quantity > 0),
                             CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- ORDER ITEM INGREDIENTS
CREATE TABLE order_item_ingredients (
                                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        order_item_id INT NOT NULL,
                                        ingredient_name VARCHAR(50) NOT NULL,
                                        CONSTRAINT fk_order_item_ing FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
);

-- ORDER ITEM EXTRAS
CREATE TABLE order_item_extras (
                                   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   order_item_id INT NOT NULL,
                                   extra_name VARCHAR(50) NOT NULL,
                                   price_cents INT NOT NULL CHECK (price_cents >= 0),
                                   CONSTRAINT fk_order_item_extra FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
);

-- DAILY ORDER COUNTER
CREATE TABLE daily_order_counter (
                                     order_date DATE PRIMARY KEY,
                                     last_number INT NOT NULL
);